name: Deploy on demo-test server

on:
  push:
    branches: [ master ]
  pull_request:
    # TODO: убрать перед вливанием
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

  env:
    REMOTE_ARCHIVE: "app.tar.gz"
    REMOTE_TMP_DIR: "~/tmp/app"
    REMOTE_APP_DIR: "~/app"

  steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Create deployment archive
      # TODO: рассмотреть возможность отказаться от команды 'mv' собирая архив сразу в текущей папке
      run: |
        tar --exclude='.git' \
            --exclude='*/bin' \
            --exclude='*/obj' \
            --exclude='${{ env.REMOTE_ARCHIVE }}' \
            -czf /tmp/${{ env.REMOTE_ARCHIVE }} .
        mv /tmp/${{ env.REMOTE_ARCHIVE }} .
      
    - name: Ensure remote tmp directory
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ env.DEPLOY_HOST }}
        username: ${{ env.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
            mkdir -p ~/tmp

    - name: Upload archive to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ env.DEPLOY_HOST }}
        username: ${{ env.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        source: ${{ env.REMOTE_ARCHIVE }}
        target: ~/tmp
  