# имя workflow
name: Example workflow

# тригер запуска
on:
  # при вливании в master
  push:
    branches: [master]
  # при открытии pull request-а на master
  pull_request:
    branches: [master]
  # вручную
  workflow_dispatch:

# этапы workflow - они же "джобы" (jobs)
jobs:
  # выполнение линтера (запуск статического анализа кода)
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore
      - name: Lint (verify no changes)
        run: dotnet format --verify-no-changes
  # выполнение юнит-тестов
  test:
    runs-on: ubuntu-latest
    steps:
      - name: No implementation
        run: echo "not implemented"
  # сборка артефакта
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: No implementation
        run: echo "not implemented"
